"""Tests for Docker scaffolding generated by create_project() / ez init."""
from __future__ import annotations

from pathlib import Path

import pytest
from click.testing import CliRunner

from ezagent.cli import cli
from ezagent.scaffold import create_project


# ---------------------------------------------------------------------------
# File creation
# ---------------------------------------------------------------------------

def test_create_project_generates_dockerfile(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    assert (tmp_path / "myapp" / "Dockerfile").is_file()


def test_create_project_generates_docker_compose(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    assert (tmp_path / "myapp" / "docker-compose.yml").is_file()


def test_create_project_generates_dockerignore(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    assert (tmp_path / "myapp" / ".dockerignore").is_file()


def test_create_project_generates_env_example(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    assert (tmp_path / "myapp" / ".env.example").is_file()


# ---------------------------------------------------------------------------
# Dockerfile content
# ---------------------------------------------------------------------------

def test_dockerfile_has_uv_base_image(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "Dockerfile").read_text()
    assert "ghcr.io/astral-sh/uv" in content


def test_dockerfile_has_workdir(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "Dockerfile").read_text()
    assert "WORKDIR /project" in content


def test_dockerfile_installs_ezagent_serve(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "Dockerfile").read_text()
    assert "ezagent[serve]" in content


def test_dockerfile_copies_project_files(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "Dockerfile").read_text()
    assert "COPY . ." in content


def test_dockerfile_starts_daemon(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "Dockerfile").read_text()
    # CMD uses JSON array form: CMD ["ez", "start"]
    assert "CMD" in content and '"ez"' in content and '"start"' in content


# ---------------------------------------------------------------------------
# docker-compose.yml content
# ---------------------------------------------------------------------------

def test_docker_compose_has_daemon_service(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "docker-compose.yml").read_text()
    assert "daemon:" in content


def test_docker_compose_has_api_service(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "docker-compose.yml").read_text()
    assert "api:" in content


def test_docker_compose_exposes_port_7771(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "docker-compose.yml").read_text()
    assert "7771" in content


def test_docker_compose_has_shared_tmp_volume(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "docker-compose.yml").read_text()
    assert "ezagent-tmp" in content


def test_docker_compose_api_depends_on_daemon(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "docker-compose.yml").read_text()
    assert "depends_on" in content


def test_docker_compose_uses_env_file(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "docker-compose.yml").read_text()
    assert "env_file" in content


def test_docker_compose_has_restart_policy(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "docker-compose.yml").read_text()
    assert "restart" in content


def test_docker_compose_mounts_project_dir(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "docker-compose.yml").read_text()
    assert ".:/project" in content


def test_docker_compose_api_runs_serve(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / "docker-compose.yml").read_text()
    assert "ez serve" in content


# ---------------------------------------------------------------------------
# .dockerignore content
# ---------------------------------------------------------------------------

def test_dockerignore_excludes_dotenv(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / ".dockerignore").read_text()
    assert ".env" in content


def test_dockerignore_excludes_ezagent_dir(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / ".dockerignore").read_text()
    assert ".ezagent/" in content


def test_dockerignore_excludes_pycache(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / ".dockerignore").read_text()
    assert "__pycache__/" in content


def test_dockerignore_excludes_git(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / ".dockerignore").read_text()
    assert ".git/" in content


# ---------------------------------------------------------------------------
# .env.example content
# ---------------------------------------------------------------------------

def test_env_example_has_anthropic_key(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / ".env.example").read_text()
    assert "ANTHROPIC_API_KEY" in content


def test_env_example_has_google_key(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / ".env.example").read_text()
    assert "GOOGLE_API_KEY" in content


def test_env_example_has_brave_key(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    create_project("myapp")
    content = (tmp_path / "myapp" / ".env.example").read_text()
    assert "BRAVE_SEARCH_API_KEY" in content


# ---------------------------------------------------------------------------
# ez init CLI — files created and mentioned in output
# ---------------------------------------------------------------------------

def test_ez_init_creates_dockerfile(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()
    result = runner.invoke(cli, ["init", "myapp"], catch_exceptions=False)
    assert result.exit_code == 0
    assert (tmp_path / "myapp" / "Dockerfile").is_file()


def test_ez_init_creates_docker_compose(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()
    result = runner.invoke(cli, ["init", "myapp"], catch_exceptions=False)
    assert result.exit_code == 0
    assert (tmp_path / "myapp" / "docker-compose.yml").is_file()


def test_ez_init_creates_env_example(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()
    result = runner.invoke(cli, ["init", "myapp"], catch_exceptions=False)
    assert result.exit_code == 0
    assert (tmp_path / "myapp" / ".env.example").is_file()


def test_ez_init_output_mentions_docker_compose(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()
    result = runner.invoke(cli, ["init", "myapp"], catch_exceptions=False)
    assert result.exit_code == 0
    assert "docker-compose.yml" in result.output


def test_ez_init_output_mentions_env_example(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()
    result = runner.invoke(cli, ["init", "myapp"], catch_exceptions=False)
    assert result.exit_code == 0
    assert ".env.example" in result.output
